### ISSUE TITLE
run ./build/bin/hsd start  show error

### ISSUE THREAD

**Issue by lulei0215** [orientwalt/htdf#17]
I[2020-12-24|14:32:16.135] Starting ABCI with Tendermint                module=main
INFO[0000] /---------flag1----------/ true
currVersion=0
LastBlockHeight=0
INFO[0000] Execute IncreaseTotalLoosenToken Successed increaseCoins 50000000000000000satoshi totalLoosenToken 50000000000000000satoshi
INFO[0000] Execute IncreaseTotalLoosenToken Successed increaseCoins 10000000000000stake totalLoosenToken 50000000000000000satoshi,10000000000000stake
INFO[0000] Execute IncreaseTotalLoosenToken Successed increaseCoins 1000000000000stake totalLoosenToken 50000000000000000satoshi,11000000000000stake
INFO[0000] Execute IncreaseTotalLoosenToken Successed increaseCoins 1000000000000stake totalLoosenToken 50000000000000000satoshi,12000000000000stake
INFO[0000] Execute IncreaseTotalLoosenToken Successed increaseCoins 1000000000000stake totalLoosenToken 50000000000000000satoshi,13000000000000stake
INFO[0000] Execute IncreaseTotalLoosenToken Successed increaseCoins 1000000000000stake totalLoosenToken 50000000000000000satoshi,14000000000000stake
panic: ERROR:
Codespace: params
Code: 201
Message: "Invalid MinDepositMultiple [0] should be between [500, 5000]"

goroutine 1 [running]:
github.com/orientwalt/htdf/x/service.InitGenesis(0x1584000, 0xc00018e7e0, 0xc000587740, 0x10, 0x1575800, 0xc000519870, 0xc0001f2e00, 0x1595480, 0xc00000cd20, 0x1575800, ...)
        /mnt/d/program/htdf/x/service/genesis.go:21 +0x26a
github.com/orientwalt/htdf/app/v0.(*ProtocolV0).initFromGenesisState(0xc000129800, 0x1584000, 0xc00018e7e0, 0xc000587740, 0x10, 0xc000bd0240, 0xc000bcec00, 0x6, 0x6, 0x0, ...)
        /mnt/d/program/htdf/app/v0/protocol_v0.go:427 +0xc38
github.com/orientwalt/htdf/app/v0.(*ProtocolV0).InitChainer(0xc000129800, 0x1584000, 0xc00018e7e0, 0xc000587740, 0x10, 0xc000bd0240, 0x2057e54e, 0xed4ca1b10, 0x0, 0xc0000c2940, ...)
        /mnt/d/program/htdf/app/v0/protocol_v0.go:467 +0x2c5
github.com/orientwalt/htdf/app.(*BaseApp).InitChain(0xc0001602a0, 0x2057e54e, 0xed4ca1b10, 0x0, 0xc0000c2940, 0x9, 0xc000586f40, 0x1ec7900, 0x0, 0x0, ...)
        /mnt/d/program/htdf/app/baseapp.go:419 +0x3c2
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000ccafc0, 0x2057e54e, 0xed4ca1b10, 0x0, 0xc0000c2940, 0x9, 0xc000586f40, 0x1ec7900, 0x0, 0x0, ...)
        /usr/local/go/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/abci/client/local_client.go:223 +0xf8
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000583a60, 0x2057e54e, 0xed4ca1b10, 0x0, 0xc0000c2940, 0x9, 0xc000586f40, 0x1ec7900, 0x0, 0x0, ...)
        /usr/local/go/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/proxy/app_conn.go:65 +0x75
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0005456d0, 0xa, 0x0, 0xc0000c2df6, 0x6, 0xc0000c2e10, 0x9, 0x0, 0x0, 0x0, ...)
        /usr/local/go/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/consensus/replay.go:305 +0x696
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0005456d0, 0x1593540, 0xc0001f3e30, 0x2, 0x15849c0)
        /usr/local/go/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/consensus/replay.go:264 +0x5b8
github.com/tendermint/tendermint/node.NewNode(0xc000177180, 0x157f5c0, 0xc0009db5e0, 0xc0001d3e30, 0x1565660, 0xc000588b20, 0xc0005820b0, 0x141ed68, 0xc000582190, 0x15849c0, ...)
        /usr/local/go/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/node/node.go:266 +0xa45
github.com/orientwalt/htdf/server.startInProcess(0xc00000ffe0, 0x141f720, 0x1d, 0x0, 0x0)
        /mnt/d/program/htdf/server/start.go:124 +0x4d6
github.com/orientwalt/htdf/server.StartCmd.func1(0xc0001a4a00, 0x1ec7900, 0x0, 0x0, 0x0, 0x0)
        /mnt/d/program/htdf/server/start.go:42 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc0001a4a00, 0x1ec7900, 0x0, 0x0, 0xc0001a4a00, 0x1ec7900)
        /usr/local/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a3ca00, 0xc000d1fed8, 0x4fb197, 0xc000173c70)
        /usr/local/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /usr/local/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000a3ca00, 0x141fb58, 0xc000d1ff68, 0x1)
        /usr/local/go/pkg/mod/github.com/orientwalt/tendermint@v90.0.7+incompatible/libs/cli/setup.go:89 +0x3c
main.main()
        /mnt/d/program/htdf/cmd/hsd/main.go:76 +0x810

**Comment by youngqqcn** [comment]
@lulei0215 

```
Message: "Invalid MinDepositMultiple [0] should be between [500, 5000]"
```

Please check your genesis file in `~/.hsd/config genesis.json` , make sure the `min_deposit_multiple` is beween 500~5000. 

By the way, if you are running the local testnet node, you could refer to [docs/build & run.md](https://github.com/orientwalt/htdf/blob/master/docs/build%20%26%20run.md).

**Comment by lulei0215** [comment]
genesis.json=》 
"service": {
      "params": {
        "max_request_timeout": "0",
        **"min_deposit_multiple": "600",**
        "service_fee_tax": "0.000000000000000000",
        "slash_fraction": "0.000000000000000000",
        "complaint_retrospect": "0",
        "arbitration_time_limit": "0",
        "tx_size_limit": "0"
      }
    },

min_deposit_multiple：600

ll@DESKTOP-V66RHRJ:/mnt/d/program$ hsd start
I[2020-12-28|14:04:25.235] Starting ABCI with Tendermint                module=main
INFO[0000] /---------flag1----------/ true
currVersion=0
LastBlockHeight=0
INFO[0000] Execute IncreaseTotalLoosenToken Successed increaseCoins 50000000000000000satoshi totalLoosenToken 50000000000000000satoshi
INFO[0000] Execute IncreaseTotalLoosenToken Successed increaseCoins 10000000000000stake totalLoosenToken 50000000000000000satoshi,10000000000000stake
INFO[0000] Execute IncreaseTotalLoosenToken Successed increaseCoins 1000000000000stake totalLoosenToken 50000000000000000satoshi,11000000000000stake
INFO[0000] Execute IncreaseTotalLoosenToken Successed increaseCoins 1000000000000stake totalLoosenToken 50000000000000000satoshi,12000000000000stake
INFO[0000] Execute IncreaseTotalLoosenToken Successed increaseCoins 1000000000000stake totalLoosenToken 50000000000000000satoshi,13000000000000stake
INFO[0000] Execute IncreaseTotalLoosenToken Successed increaseCoins 1000000000000stake totalLoosenToken 50000000000000000satoshi,14000000000000stake
panic: ERROR:
Codespace: params
Code: 201
Message: "Invalid MinDepositMultiple [0] should be between [500, 5000]"

**Comment by lulei0215** [comment]
设置了500-5000的数值   hsd run 还是报这个错

**Comment by youngqqcn** [comment]
Do not edit `genesis.json` manually.  For quick start, you could use `make new` to initialize the genesis config of the blockchain , and start the local test node by `make start`. The node log file in `~/.hsd/app.log`. More details in `docs`.

快速启动: 可以使用`make new`进行代码编译和配置初始化, 使用 `make start`启动, 日志文件在 `~/.hsd/app.log`.  
更多细节可以参考 docs下的文档, 如: [build & run](https://github.com/orientwalt/htdf/blob/master/docs/build%20%26%20run.md) ).
