### ISSUE TITLE
junying/event_filter: suspicious "out of gas" when send htdf to contract address

### ISSUE THREAD

**Issue by deep2chain** [orientwalt/htdf#52]
```
{
  "height": "772",
  "txhash": "4584D7B9BDFDE0A529FA924616B3B1740CEE1B4562CED497692331BF671053C3",
  "data": "BB020A140000000000000000000000000000000000000000128002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002A204584D7B9BDFDE0A529FA924616B3B1740CEE1B4562CED497692331BF671053C3",
  "raw_log": "[{\"msg_index\":\"0\",\"success\":false,\"log\":\"executed EVM state transition; sender address: 0x85cED8Ddf399D75c9E381E01F3bddCeFb9132Fe9, recipient address: 0x4481fEe129f2d6b9dbd0BF40880B2662FD5Eb077, output: , err: out of gas\"}]",
  "logs": [
    {
      "msg_index": "0",
      "success": false,
      "log": "executed EVM state transition; sender address: 0x85cED8Ddf399D75c9E381E01F3bddCeFb9132Fe9, recipient address: 0x4481fEe129f2d6b9dbd0BF40880B2662FD5Eb077, output: , err: out of gas"
    }
  ],
  "gas_wanted": "30000",
  "tx": {
    "type": "auth/StdTx",
    "value": {
      "msg": [
        {
          "type": "htdfservice/send",
          "value": {
            "From": "htdf1sh8d3h0nn8t4e83crcql80wua7u3xtlfj5dej3",
            "To": "htdf1gjqlacff7tttnk7shaqgszexvt74avrh507knj",
            "Amount": [
              {
                "denom": "satoshi",
                "amount": "11"
              }
            ],
            "Data": "",
            "GasPrice": "100",
            "GasWanted": "30000"
          }
        }
      ],
      "fee": {
        "gas_wanted": "30000",
        "gas_price": "100"
      },
      "signatures": [
        {
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "A2t2ZhUf8W2rq3TEDCmYJCJ7Qrermowx4TR5MzDC4nOE"
          },
          "signature": "kcNkpclhQcdFPNUHGrTBOWi0KHDNzzK/TZ8PZ0vgQHMmjuK7PQe33th7I8Vm9lR+q1mcWqpo45XGrVlL78mBQw=="
        }
      ],
      "memo": ""
    }
  },
  "timestamp": "2021-03-29T06:52:46Z"
}

```

**Comment by youngqqcn** [comment]
Did the contract had  **public payable fallback function** ?  Such as `function () payable public {}`.

**Comment by youngqqcn** [comment]
Did the contract had  **public payable fallback function** ?  Such as `function () payable public {}`.

**Comment by deep2chain** [comment]
No, what i did is like follows
```
account: htdfxxx
contract address: htdfyyy

$ hscli tx send htdfxxx htdfyyy 100000satoshi --gas-price=100
```

**Comment by youngqqcn** [comment]
> No, what i did is like follows
> 
> ```
> account: htdfxxx
> contract address: htdfyyy
> 
> $ hscli tx send htdfxxx htdfyyy 100000satoshi --gas-price=100
> ```

Due to the `Data` of tx is empty,  if the contact's code exists this normal transaction will call the fallback function of the contract. If fallback function does not exists or fallback function couldn't be called, this tx will be reverted.

**Comment by deep2chain** [comment]
your explanation is reasonable. But I am still wondering if the logic is fault-proof. Suppose that an normal address is coincident with certain contract address. It's rare case, but still possible. In that case, you can't use that account again because same contract address exists

**Comment by youngqqcn** [comment]
> your explanation is reasonable. But I am still wondering if the logic is fault-proof. Suppose that an normal address is coincident with certain contract address. It's rare case, but still possible. In that case, you can't use that account again because same contract address exists

Firstly, we use formular to explain how the contract address be generated:

 `C = H( A, N )`

- `C`: contract address
- `H`: a hash function , e.g. `Keccak256`
- `A`: the creator address , may be a normal address or contract address
- `N`: the `nonce` of `A`

Secondly, you said :
> Suppose that an normal address is coincident with certain contract address. It's rare case, but still possible. In that case, you can't use that account again because same contract address exists

two points:

1. Ethereum address is the partial hash of public key . Public key is be deduced by private key. The private key is the everything of acount. The private key is a big number about in range `0 ~ 2^256`. Private key collision is just a theoretical assumption. At least, it's impossible in reality now.

2. If a contract address is used before a contract be created, it MUST be ARTIFICAL. In this case, the address will be like `normal address` until contract be created and the code be attached on it.
