### ISSUE TITLE
no deletegation rewards withdraw records 

### ISSUE THREAD

**Issue by youngqqcn** [orientwalt/htdf#7]
no deletegation rawards withdraw records , when  an account  which had delegated some coins before and not unbond yet deletegate some coins again , the rewards of old delegation will be send to this delegator  by code logic .

https://github.com/orientwalt/htdf/blob/a3cd243e67747a3bd618d19bc5f9a73b4c24932b/x/distribution/keeper/delegation.go#L156

**Comment by youngqqcn** [comment]
To  fix issue  we should show some informations about this  *AUTOMATIC* rewards withdraw operations .

**Comment by renanbastos93** [comment]
I saw this issue on filter golang on Github, Can you explain more about it? I want to contribute.

**Comment by youngqqcn** [comment]
This issue had be fixed in release v1.2.1
