### ISSUE TITLE
[HTDF2.0] `/staking/delegators/{delegatorAddr}/unbonding_delegations/{validatorAddr}` internal error

### ISSUE THREAD

**Issue by youngqqcn** [orientwalt/htdf#87]
```
curl http://127.0.0.1:1317/staking/delegators/htdf1gjsqy9weuv994pq83jdqldrzuhctvyuudtdga7/unbonding_delegations/htdfvaloper1vg9ray8kzjtzagnt5xhuq7qrn0uf4lf0c2g2lr

```

**Comment by youngqqcn** [comment]
https://github.com/orientwalt/htdf/blob/34a9c2b78a69be04960597cc8c3820e71f77cb41/x/staking/client/rest/utils.go#L60

**Comment by youngqqcn** [comment]
```go

// return a unbonding delegation
func (k Keeper) GetUnbondingDelegation(ctx sdk.Context,
	delAddr sdk.AccAddress, valAddr sdk.ValAddress) (ubd types.UnbondingDelegation, found bool) {

	store := ctx.KVStore(k.storeKey)
	key := GetUBDKey(delAddr, valAddr)
	value := store.Get(key)
	if value == nil {  //=================  Why value is nil ??
		return ubd, false
	}

	ubd = types.MustUnmarshalUBD(k.cdc, value)
	return ubd, true
}
```

**Comment by deep2chain** [comment]
```
curl -X GET "http://localhost:1317/staking/delegators/htdf1v8j6r7ttfac07nuhy8uhxgumy7442ck5mnj7fx/delegations/htdfvaloper1v8j6r7ttfac07nuhy8uhxgumy7442ck532287d" -H "accept: application/json"
```

**Comment by youngqqcn** [comment]
@deep2chain

**Comment by deep2chain** [comment]
@youngqqcn I think the query format is like the below. Are you sure it contains validator address?
```
$ curl -X GET "http://localhost:1317/staking/delegators/htdf1w29gjnsmmjwk/unbonding_delegations" -H "accept: application/json"
```

**Comment by youngqqcn** [comment]
> @youngqqcn I think the query format is like the below. Are you sure it contains validator address?
> 
> ```
> $ curl -X GET "http://localhost:1317/staking/delegators/htdf1w29gjnsmmjwk/unbonding_delegations" -H "accept: application/json"
> ```

@deep2chain 

`/staking/delegators/{delegatorAddr}/unbonding_delegations` is query all of a delegators's unbonding-delegations from **many** validators. 

`/staking/delegators/{delegatorAddr}/unbonding_delegations/{validatorAddr}`  is query all of a delegators's unbonding-delegations from **one** validators.
